version: "3"

services:
  db:
    image: mariadb:10.9.4
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - db_data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ./db/.env.cnf
    environment:
      TZ: Asia/Seoul
    restart: always

  web:
    image: golang:1.19.4
    ports:
      - 80:9999
    volumes:
      - ./web:$GOPATH/src
    depends_on:
      - db

volumes:
  db_data: {}